# Introduction to RBF networks

The objective of this notebook is to introduce the reader to radial basis function feedforward neural networks.

In [1]:
import sklearn
sklearn.__version__

'0.19.dev0'

In [2]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [38]:
import os
import sys
import inspect

currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent =  os.path.dirname(currentdir) + '/RBFClassifier'
sys.path.insert(0,parent)

import numpy as np

In [39]:
from sklearn import datasets

In [40]:
digits = datasets.load_digits()
X = digits.data
y = digits.target

### Parameters of the RBF network

In [53]:
import rbf_classifier_classic
from rbf_classifier_classic import RBFClassifier as RBFClassifierClassic

In [54]:
rbf_classic = RBFClassifierClassic(n_hidden_basis=20)

In [55]:
rbf_classic.get_params()

{'KMeans_flag': True,
 'n_hidden_basis': 20,
 'random_state': 1234,
 'stratified_basis_selection': True}

## Train RBF network

In [56]:
X.shape, y.shape

((1797, 64), (1797,))

In [58]:
rbf_classic.fit(X, y)

RBFClassifier(KMeans_flag=True, n_hidden_basis=20, random_state=1234,
       stratified_basis_selection=True)

### Making predictions

In [59]:
rbf_classic.forward_propagation(X[0:20]).shape

(20, 10)

In [60]:
rbf_classic.predict(X[0:5])

array([0, 1, 1, 3, 4])

In [61]:
rbf_classic.forward_propagation(X[0:2])

array([[  4.42883191e-02,   1.70678140e-16,  -7.19906504e-15,
         -2.44531610e-17,   5.08643382e-17,  -5.14807425e-16,
         -6.38062659e-18,  -7.10508186e-17,  -3.99527099e-17,
         -1.72322259e-13],
       [ -5.07590911e-25,   1.19133978e-10,  -5.85741548e-25,
         -1.13565820e-23,   6.12177380e-27,  -4.19126122e-24,
         -1.60854356e-25,  -2.71797290e-24,  -8.51515975e-19,
         -1.22041590e-23]])

In [62]:
rbf_classic.predict_proba(X[0:2])

array([[  1.00000000e+00,   3.85379583e-15,  -1.62549972e-13,
         -5.52135676e-16,   1.14848202e-15,  -1.16240001e-14,
         -1.44070191e-16,  -1.60427896e-15,  -9.02104904e-16,
         -3.89091893e-12],
       [ -4.26067291e-15,   1.00000001e+00,  -4.91666239e-15,
         -9.53261381e-14,   5.13856241e-17,  -3.51810735e-14,
         -1.35019714e-15,  -2.28144225e-14,  -7.14754927e-09,
         -1.02440624e-13]])

In [63]:
rbf_classic.score(X,y)

0.9003895381190874

### Gridsearch n_hidden_basis

In [64]:
from sklearn.model_selection import GridSearchCV

In [65]:
param_grid = {"n_hidden_basis": list(range(10,100,5))}

In [66]:
rbf_classic.get_params()

{'KMeans_flag': True,
 'n_hidden_basis': 20,
 'random_state': 1234,
 'stratified_basis_selection': True}

In [67]:
rbf_classic = RBFClassifierClassic()

In [68]:
grid_rbf_classic = GridSearchCV(estimator=rbf_classic, 
                               param_grid=param_grid,
                               n_jobs=1)

In [71]:
grid_rbf_classic.fit(X,y)

GridSearchCV(cv=None, error_score='raise',
       estimator=RBFClassifier(KMeans_flag=True, n_hidden_basis=50, random_state=1234,
       stratified_basis_selection=True),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_hidden_basis': [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [72]:
grid_rbf_classic.grid_scores_

/Users/david/anaconda/lib/python3.5/site-packages/sklearn/model_selection/_search.py:663: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)


[mean: 0.72343, std: 0.04335, params: {'n_hidden_basis': 10},
 mean: 0.85476, std: 0.00725, params: {'n_hidden_basis': 15},
 mean: 0.86867, std: 0.02572, params: {'n_hidden_basis': 20},
 mean: 0.86700, std: 0.03875, params: {'n_hidden_basis': 25},
 mean: 0.90373, std: 0.02282, params: {'n_hidden_basis': 30},
 mean: 0.90428, std: 0.01697, params: {'n_hidden_basis': 35},
 mean: 0.90206, std: 0.02171, params: {'n_hidden_basis': 40},
 mean: 0.84140, std: 0.06243, params: {'n_hidden_basis': 45},
 mean: 0.79967, std: 0.10452, params: {'n_hidden_basis': 50},
 mean: 0.83306, std: 0.02842, params: {'n_hidden_basis': 55},
 mean: 0.83695, std: 0.05699, params: {'n_hidden_basis': 60},
 mean: 0.80523, std: 0.05352, params: {'n_hidden_basis': 65},
 mean: 0.81747, std: 0.07289, params: {'n_hidden_basis': 70},
 mean: 0.74235, std: 0.03075, params: {'n_hidden_basis': 75},
 mean: 0.70729, std: 0.01347, params: {'n_hidden_basis': 80},
 mean: 0.74736, std: 0.03075, params: {'n_hidden_basis': 85},
 mean: 0