# Introduction to RBF networks

The objective of this notebook is to introduce the reader to radial basis function feedforward neural networks.

In [ ]:
import sklearn
sklearn.__version__

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import os
import sys
import inspect

currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent =  os.path.dirname(currentdir) + '/RBFClassifier'
sys.path.insert(0,parent)

import numpy as np

In [3]:
from sklearn import datasets

In [4]:
digits = datasets.load_digits()
X = digits.data
y = digits.target

### Parameters of the RBF network

In [5]:
import rbf_classifier_classic
from rbf_classifier_classic import RBFClassifier as RBFClassifierClassic

In [6]:
rbf_classic = RBFClassifierClassic(n_hidden_basis=20)

In [7]:
rbf_classic.get_params()

{'KMeans_flag': True,
 'n_hidden_basis': 20,
 'random_state': 1234,
 'stratified_basis_selection': True}

## Train RBF network

In [8]:
X.shape, y.shape

((1797, 64), (1797,))

In [9]:
y = y.reshape(-1,1)

In [10]:
rbf_classic.fit(X, y)

RBFClassifier(KMeans_flag=True, n_hidden_basis=20, random_state=1234,
       stratified_basis_selection=True)

### Making predictions

In [11]:
rbf_classic.forward_propagation(X[0:20]).shape

(20, 10)

In [12]:
rbf_classic.predict(X[0:5])

array([0, 1, 1, 3, 4])

In [13]:
rbf_classic.forward_propagation(X[0:2])

array([[  4.42883191e-02,   1.70678140e-16,  -7.19906504e-15,
         -2.44531610e-17,   5.08643382e-17,  -5.14807425e-16,
         -6.38062659e-18,  -7.10508186e-17,  -3.99527099e-17,
         -1.72322259e-13],
       [ -5.07590911e-25,   1.19133978e-10,  -5.85741548e-25,
         -1.13565820e-23,   6.12177380e-27,  -4.19126122e-24,
         -1.60854356e-25,  -2.71797290e-24,  -8.51515975e-19,
         -1.22041590e-23]])

In [14]:
rbf_classic.predict_proba(X[0:2])

array([[  1.00000000e+00,   3.85379583e-15,  -1.62549972e-13,
         -5.52135676e-16,   1.14848202e-15,  -1.16240001e-14,
         -1.44070191e-16,  -1.60427896e-15,  -9.02104904e-16,
         -3.89091893e-12],
       [ -4.26067291e-15,   1.00000001e+00,  -4.91666239e-15,
         -9.53261381e-14,   5.13856241e-17,  -3.51810735e-14,
         -1.35019714e-15,  -2.28144225e-14,  -7.14754927e-09,
         -1.02440624e-13]])

In [15]:
rbf_classic.score(X,y)

0.9003895381190874

### Gridsearch n_hidden_basis

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
param_grid = {"n_hidden_basis": list(range(10,100,5))}

In [18]:
rbf_classic.get_params()

{'KMeans_flag': True,
 'n_hidden_basis': 20,
 'random_state': 1234,
 'stratified_basis_selection': True}

In [19]:
rbf_classic = RBFClassifierClassic(n_hidden_basis=10)

In [20]:
grid_rbf_classic = GridSearchCV(estimator=rbf_classic, 
                               param_grid=param_grid,
                               n_jobs=1)

In [21]:
grid_rbf_classic.fit(X,y)

IndexError: too many indices for array